# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-23 14:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuentry',
            name='label',
            field=models.TextField(),
        ),
    ]
