# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-25 08:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20160723_1414'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('category_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='MenuEntry',
        ),
    ]
