# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-26 11:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='slug',
            field=models.SlugField(default='unset', max_length=100),
        ),
    ]
