# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-30 06:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_theme_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField()),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(default='unset', max_length=100)),
                ('text', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'footer categories',
            },
        ),
    ]
