# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-30 06:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_footercategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, default='unset', max_length=100),
        ),
    ]
