# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-01 05:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0016_auto_20160819_1005'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='published_on_home_page',
            field=models.BooleanField(default=True),
        ),
    ]
