# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-30 13:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0017_news_published_on_home_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='tile',
            name='published',
            field=models.BooleanField(default=True),
        ),
    ]
